# Generated by Django 3.1 on 2020-08-12 13:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("group", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="linkedusergroup", unique_together={("group", "member")},
        ),
    ]
